---
title: "Mocap Data Cleaning Script"
output: html_notebook
---

**Purpose**

The purpose of this script is to clean the mocap data and does the following: 
1. Convert time from seconds to milliseconds
2. Change title names

```{r, warning=FALSE}

# Load necessary packages
library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)
library(corrr)
library(reshape2)
```

```{r}

# Load data
sensor_data <- read_csv("/Users/teresanguyen/Documents/Faboratory Stuff/soft-robotics-simulations/data/raise_rhand_sensor.csv", show_col_types=FALSE)
# remove all unnecessary headers
mocap_data <- read.csv("/Users/teresanguyen/Documents/Faboratory Stuff/soft-robotics-simulations/data/raise_rhand_mocap.csv", skip = 3)
mocap_data <- mocap_data[-1,]
head(sensor_data)

```

```{r}

# Load data
# # Remove all the columns we don't need based on the suit
# mocap_data <- mocap_data[, !(unlist(mocap_data[2, ]) %in% c("Skeleton 001:Skeleton 001", "Skeleton 001:Head", "Skeleton 001:Neck", "Skeleton 001:LHand", "Skeleton 001:LThumb1", "Skeleton 001:LThumb2", "Skeleton 001:LThumb3", "Skeleton 001:LIndex1", "Skeleton 001:LIndex2", "Skeleton 001:LIndex3", "Skeleton 001:LMiddle1", "Skeleton 001:LMiddle2", "Skeleton 001:LMiddle3", "Skeleton 001:LRing1", "Skeleton 001:LRing2", "Skeleton 001:LRing3", "Skeleton 001:LPinky1", "Skeleton 001:LPinky2", "Skeleton 001:LPinky3", "Skeleton 001:RHand", "Skeleton 001:RThumb1","Skeleton 001:RThumb2", "Skeleton 001:RThumb3", "Skeleton 001:RIndex1", "Skeleton 001:RIndex2", "Skeleton 001:RIndex3", "Skeleton 001:RMiddle1", "Skeleton 001:RMiddle2", "Skeleton 001:RMiddle3", "Skeleton 001:RRing1", "Skeleton 001:RRing2", "Skeleton 001:RRing3", "Skeleton 001:RPinky1", "Skeleton 001:RPinky2", "Skeleton 001:RPinky3", "Skeleton 001:LFoot", "Skeleton 001:LToe", "Skeleton 001:RFoot", "Skeleton 001:RToe", "Skeleton 001:LFHD", "Skeleton 001:RBHD", "Skeleton 001:LBHD", "Skeleton 001:RFHD", "Skeleton 001:C7", "Skeleton 001:LUArm", "Skeleton 001:LFArm", "Skeleton 001:LFIN", "Skeleton 001:RUArm", "Skeleton 001:RFArm", "Skeleton 001:RFIN", "Skeleton 001:LASI", "Skeleton 001:LPSI", "Skeleton 001:RPSI", "Skeleton 001:RASI", "Skeleton 001:LThigh", "Skeleton 001:LANK", "Skeleton 001:LHEE", "Skeleton 001:LTOE", "Skeleton 001:RThigh", "Skeleton 001:RANK", "Skeleton 001:RHEE", "Skeleton 001:RTOE", "Skeleton 001:LANK", "Skeleton 001:LASI", "Skeleton 001:RShin", "Skeleton 001:LTHI", "Skeleton 001:LKNE", "left_tibia", "Skeleton 001:RTHI", "Skeleton 001:RKNE", "Skeleton 001:LShin") | is.na(unlist(mocap_data[2, ])))]
# 
# # check the column names
# mocap_data[2, ]

# Remove columns that aren't needed 
mocap_data <- mocap_data[, !(colnames(mocap_data) %in% c("Skeleton.002.Skeleton.002", "Skeleton.002.Skeleton.002.1", "Skeleton.002.Skeleton.002.2", "Skeleton.002.Skeleton.002.3", "Skeleton.002.Skeleton.002.4", "Skeleton.002.Skeleton.002.5", "Skeleton.002.Skeleton.002.6",   "dancepad.Marker.001.3_X",   "dancepad.Marker.001.3", "dancepad.Marker.001.4", "dancepad.Marker.001.5",
  "dancepad.Marker.0010.3", "dancepad.Marker.0010.4", "dancepad.Marker.0010.5",
  "dancepad.Marker.002.3", "dancepad.Marker.002.4", "dancepad.Marker.002.5",
  "dancepad.Marker.003.3", "dancepad.Marker.003.4", "dancepad.Marker.003.5",
  "dancepad.Marker.004.3", "dancepad.Marker.004.4", "dancepad.Marker.004.5",
  "dancepad.Marker.005.3", "dancepad.Marker.005.4", "dancepad.Marker.005.5",
  "dancepad.Marker.006.3", "dancepad.Marker.006.4", "dancepad.Marker.006.5",
  "dancepad.Marker.007.3", "dancepad.Marker.007.4", "dancepad.Marker.007.5",
  "dancepad.Marker.008.3", "dancepad.Marker.008.4", "dancepad.Marker.008.5",
  "dancepad.Marker.009.3", "dancepad.Marker.009.4", "dancepad.Marker.009.5",
  "dancepad.Marker.011.3", "dancepad.Marker.011.4", "dancepad.Marker.011.5", "dancepad", "dancepad.1", "dancepad.2", "dancepad.3", "dancepad.4",
  "dancepad.5", "dancepad.6", "dancepad.Marker.001", "dancepad.Marker.001.1", "dancepad.Marker.001.2",
  "dancepad.Marker.002", "dancepad.Marker.002.1", "dancepad.Marker.002.2", "dancepad.Marker.003",
  "dancepad.Marker.003.1", "dancepad.Marker.003.2", "dancepad.Marker.004", "dancepad.Marker.004.1",
  "dancepad.Marker.004.2", "dancepad.Marker.005", "dancepad.Marker.005.1", "dancepad.Marker.005.2",
  "dancepad.Marker.006", "dancepad.Marker.006.1", "dancepad.Marker.006.2", "dancepad.Marker.007",
  "dancepad.Marker.007.1", "dancepad.Marker.007.2", "dancepad.Marker.008", "dancepad.Marker.008.1",
  "dancepad.Marker.008.2", "dancepad.Marker.009", "dancepad.Marker.009.1", "dancepad.Marker.009.2",
  "dancepad.Marker.0010", "dancepad.Marker.0010.1", "dancepad.Marker.0010.2", "dancepad.Marker.011",
  "dancepad.Marker.011.1", "dancepad.Marker.011.2"))]

colnames(mocap_data)
# Check result
head(mocap_data)

```

```{r}

# # Vicon dictionary
# joint_map <- c(
#   "Skeleton 001:Ab"    = "abdomen",
#   "Skeleton 001:Chest" = "chest",
#   "Skeleton 001:LShoulder" = "left_shoulder",
#   # "Skeleton 001:LUArm" = "left_upper_arm",
#   # "Skeleton 001:LFArm" = "left_forearm",
#   "Skeleton 001:RShoulder" = "right_shoulder",
#   # "Skeleton 001:RUArm" = "right_upper_arm",
#   "Skeleton 001:RFArm" = "right_forearm",
#   # "Skeleton 001:LThigh" = "left_thigh",
#   "Skeleton 001:LShin" = "left_shin",
#   # "Skeleton 001:RThigh" = "right_thigh",
#   "Skeleton 001:RShin" = "right_shin",
#   "Skeleton 001:T10" = "10th_thoracic_vertebra",
#   "Skeleton 001:RBAK" = "right_back",
#   "Skeleton 001:CLAV" = "clavicle",
#   "Skeleton 001:STRN" = "sternum",
#   "Skeleton 001:LSHO" = "left_shoulder",
#   "Skeleton 001:LUPA" = "left_upper_arm",
#   "Skeleton 001:LELB" = "left_elbow",
#   "Skeleton 001:LFRM" = "left_forearm",
#   "Skeleton 001:LWRB" = "left_wrist_b",
#   "Skeleton 001:LWRA" = "left_wrist_a",
#   "Skeleton 001:RSHO" = "right_shoulder",
#   "Skeleton 001:RUPA" = "right_upper_arm",
#   "Skeleton 001:RELB" = "right_elbow",
#   "Skeleton 001:RFRM" = "right_forearm",
#   "Skeleton 001:RWRB" = "right_wrist_b",
#   "Skeleton 001:RWRA" = "right_wrist_a",
#   "Skeleton 001:RFIN" = "right_finger",
#   "Skeleton 001:LTHI" = "left_thigh",
#   "Skeleton 001:LKNE" = "left_knee",
#   "Skeleton 001:LTIB" = "left_tibia",
#   # "Skeleton 001:LANK" = "left_ankle",
#   # "Skeleton 001:LHEE" = "left_heel",
#   "Skeleton 001:RTHI" = "right_thigh",
#   "Skeleton 001:RKNE" = "right_knee",
#   "Skeleton 001:RTIB" = "right_tibia",
#   "Skeleton 001:CLAV" = "clavicle",
#   "Skeleton 001:LFIN" = "left_finger"
# )

# joint_map <- c(
#   "Skeleton 001:Ab"        = "abdomen",
#   "Skeleton 001:Chest"     = "chest",
#   "Skeleton 001:LShoulder" = "left_shoulder",
#   "Skeleton 001:RShoulder" = "right_shoulder",
#   "Skeleton 001:RFArm"     = "right_forearm",
#   "Skeleton 001:LShin"     = "left_shin",
#   "Skeleton 001:RShin"     = "right_shin",
#   "Skeleton 001:T10"       = "t10",
#   "Skeleton 001:RBAK"      = "right_back",
#   "Skeleton 001:CLAV"      = "clavicle",
#   "Skeleton 001:STRN"      = "sternum",
# 
#   # Extended joint mapping from removed entries
#   "Skeleton 001:Head"      = "head",
#   "Skeleton 001:Neck"      = "neck",
#   "Skeleton 001:LHand"     = "left_hand",
#   "Skeleton 001:RHand"     = "right_hand",
#   "Skeleton 001:LThumb1"   = "left_thumb1",
#   "Skeleton 001:LThumb2"   = "left_thumb2",
#   "Skeleton 001:LThumb3"   = "left_thumb3",
#   "Skeleton 001:LIndex1"   = "left_index1",
#   "Skeleton 001:LIndex2"   = "left_index2",
#   "Skeleton 001:LIndex3"   = "left_index3",
#   "Skeleton 001:LMiddle1"  = "left_middle1",
#   "Skeleton 001:LMiddle2"  = "left_middle2",
#   "Skeleton 001:LMiddle3"  = "left_middle3",
#   "Skeleton 001:LRing1"    = "left_ring1",
#   "Skeleton 001:LRing2"    = "left_ring2",
#   "Skeleton 001:LRing3"    = "left_ring3",
#   "Skeleton 001:LPinky1"   = "left_pinky1",
#   "Skeleton 001:LPinky2"   = "left_pinky2",
#   "Skeleton 001:LPinky3"   = "left_pinky3",
#   "Skeleton 001:RThumb1"   = "right_thumb1",
#   "Skeleton 001:RThumb2"   = "right_thumb2",
#   "Skeleton 001:RThumb3"   = "right_thumb3",
#   "Skeleton 001:RIndex1"   = "right_index1",
#   "Skeleton 001:RIndex2"   = "right_index2",
#   "Skeleton 001:RIndex3"   = "right_index3",
#   "Skeleton 001:RMiddle1"  = "right_middle1",
#   "Skeleton 001:RMiddle2"  = "right_middle2",
#   "Skeleton 001:RMiddle3"  = "right_middle3",
#   "Skeleton 001:RRing1"    = "right_ring1",
#   "Skeleton 001:RRing2"    = "right_ring2",
#   "Skeleton 001:RRing3"    = "right_ring3",
#   "Skeleton 001:RPinky1"   = "right_pinky1",
#   "Skeleton 001:RPinky2"   = "right_pinky2",
#   "Skeleton 001:RPinky3"   = "right_pinky3",
#   "Skeleton 001:LFoot"     = "left_foot",
#   "Skeleton 001:LToe"      = "left_toe",
#   "Skeleton 001:RFoot"     = "right_foot",
#   "Skeleton 001:RToe"      = "right_toe",
#   "Skeleton 001:LFHD"      = "left_forehead",
#   "Skeleton 001:RBHD"      = "right_back_head",
#   "Skeleton 001:LBHD"      = "left_back_head",
#   "Skeleton 001:RFHD"      = "right_forehead",
#   "Skeleton 001:LUArm"     = "left_upper_arm",
#   "Skeleton 001:LFArm"     = "left_forearm",
#   "Skeleton 001:RUArm"     = "right_upper_arm",
#   "Skeleton 001:LASI"      = "left_asi",
#   "Skeleton 001:LPSI"      = "left_psi",
#   "Skeleton 001:RPSI"      = "right_psi",
#   "Skeleton 001:RASI"      = "right_asi",
#   "Skeleton 001:LThigh"    = "left_thigh",
#   "Skeleton 001:LANK"      = "left_ankle",
#   "Skeleton 001:LHEE"      = "left_heel",
#   "Skeleton 001:LTOE"      = "left_toe_marker",
#   "Skeleton 001:RThigh"    = "right_thigh",
#   "Skeleton 001:RANK"      = "right_ankle",
#   "Skeleton 001:RHEE"      = "right_heel",
#   "Skeleton 001:RTOE"      = "right_toe_marker",
#   "Skeleton 001:LTHI"      = "left_thigh_alt",
#   "Skeleton 001:LKNE"      = "left_knee",
#   "Skeleton 001:LTIB"      = "left_tibia",
#   "Skeleton 001:RTHI"      = "right_thigh_alt",
#   "Skeleton 001:RKNE"      = "right_knee",
#   "Skeleton 001:RTIB"      = "right_tibia",
#   "Skeleton 001:LFIN"      = "left_finger",
#   "Skeleton 001:RFIN"      = "right_finger"
# )

joint_map <- c(
  Skeleton.002.Ab = "abdomen",
  Skeleton.002.Chest = "chest",
  Skeleton.002.LShoulder = "left_shoulder",
  Skeleton.002.RShoulder = "right_shoulder",
  Skeleton.002.RFArm = "right_forearm",
  Skeleton.002.LShin = "left_shin",
  Skeleton.002.RShin = "right_shin",
  Skeleton.002.T10 = "t10",
  Skeleton.002.RBAK = "right_back",
  Skeleton.002.CLAV = "clavicle",
  Skeleton.002.STRN = "sternum",
  Skeleton.002.Head = "head",
  Skeleton.002.Neck = "neck",
  Skeleton.002.LHand = "left_hand",
  Skeleton.002.RHand = "right_hand",
  Skeleton.002.LThumb1 = "left_thumb1",
  Skeleton.002.LThumb2 = "left_thumb2",
  Skeleton.002.LThumb3 = "left_thumb3",
  Skeleton.002.LIndex1 = "left_index1",
  Skeleton.002.LIndex2 = "left_index2",
  Skeleton.002.LIndex3 = "left_index3",
  Skeleton.002.LMiddle1 = "left_middle1",
  Skeleton.002.LMiddle2 = "left_middle2",
  Skeleton.002.LMiddle3 = "left_middle3",
  Skeleton.002.LRing1 = "left_ring1",
  Skeleton.002.LRing2 = "left_ring2",
  Skeleton.002.LRing3 = "left_ring3",
  Skeleton.002.LPinky1 = "left_pinky1",
  Skeleton.002.LPinky2 = "left_pinky2",
  Skeleton.002.LPinky3 = "left_pinky3",
  Skeleton.002.RThumb1 = "right_thumb1",
  Skeleton.002.RThumb2 = "right_thumb2",
  Skeleton.002.RThumb3 = "right_thumb3",
  Skeleton.002.RIndex1 = "right_index1",
  Skeleton.002.RIndex2 = "right_index2",
  Skeleton.002.RIndex3 = "right_index3",
  Skeleton.002.RMiddle1 = "right_middle1",
  Skeleton.002.RMiddle2 = "right_middle2",
  Skeleton.002.RMiddle3 = "right_middle3",
  Skeleton.002.RRing1 = "right_ring1",
  Skeleton.002.RRing2 = "right_ring2",
  Skeleton.002.RRing3 = "right_ring3",
  Skeleton.002.RPinky1 = "right_pinky1",
  Skeleton.002.RPinky2 = "right_pinky2",
  Skeleton.002.RPinky3 = "right_pinky3",
  Skeleton.002.LFoot = "left_foot",
  Skeleton.002.LToe = "left_toe",
  Skeleton.002.RFoot = "right_foot",
  Skeleton.002.RToe = "right_toe",
  Skeleton.002.LFHD = "left_forehead",
  Skeleton.002.RBHD = "right_back_head",
  Skeleton.002.LBHD = "left_back_head",
  Skeleton.002.RFHD = "right_forehead",
  Skeleton.002.LUArm = "left_upper_arm",
  Skeleton.002.LFArm = "left_forearm",
  Skeleton.002.RUArm = "right_upper_arm",
  Skeleton.002.LASI = "left_asi",
  Skeleton.002.LPSI = "left_psi",
  Skeleton.002.RPSI = "right_psi",
  Skeleton.002.RASI = "right_asi",
  Skeleton.002.LThigh = "left_thigh",
  Skeleton.002.LANK = "left_ankle",
  Skeleton.002.LHEE = "left_heel",
  Skeleton.002.LTOE = "left_toe_marker",
  Skeleton.002.RThigh = "right_thigh",
  Skeleton.002.RANK = "right_ankle",
  Skeleton.002.RHEE = "right_heel",
  Skeleton.002.RTOE = "right_toe_marker",
  Skeleton.002.LTHI = "left_thigh_alt",
  Skeleton.002.LKNE = "left_knee",
  Skeleton.002.LTIB = "left_tibia",
  Skeleton.002.RTHI = "right_thigh_alt",
  Skeleton.002.RKNE = "right_knee",
  Skeleton.002.RTIB = "right_tibia",
  Skeleton.002.LFIN = "left_finger",
  Skeleton.002.RFIN = "right_finger",
  Skeleton.002.LSHO = "left_shoulder",
  Skeleton.002.LELB = "left_elbow",
  Skeleton.002.LWRB = "left_wrist_b",
  Skeleton.002.LWRA = "left_wrist_a",
  Skeleton.002.RSHO = "right_shoulder",
  Skeleton.002.RELB = "right_elbow",
  Skeleton.002.RUPA = "right_upper_arm",
  Skeleton.002.C7 = "7_cervical_vertebra",
  Skeleton.002.LUPA = "left_upper_arm",
  Skeleton.002.LFRM = "left_forearm",
  Skeleton.002.RWRB = "right_wrist_b",
  Skeleton.002.RWRA = "right_wrist_a",
  Skeleton.002.RFRM = "right_forearm"
  
)

```

```{r}


# original joint names extracted
colnames(mocap_data)
# Remove suffixes like ".1", ".6", etc. from the original names
original_joint_names <- colnames(mocap_data)

clean_joint_names <- sub("\\.[0-9]+$", "", original_joint_names)

# Replace using the dictionary
renamed_joint_names <- ifelse(
  clean_joint_names %in% names(joint_map),
  joint_map[clean_joint_names],
  original_joint_names
)

# extract data type and axis for combination
axis <- unlist(mocap_data[2, ])

new_colnames <- paste(renamed_joint_names, axis, sep = "_")

# Remove spaces and NA
new_colnames <- gsub("NA", "", new_colnames)
new_colnames <- gsub("__", "_", new_colnames)

mocap_data <- mocap_data[-c(1:2), ]
colnames(mocap_data) <- new_colnames
colnames(mocap_data)[2] <- "time_ms"
colnames(mocap_data)[1] <- "Frame"

# Checks
head(mocap_data)
colnames(mocap_data)

```
```{r}

mocap_data$time_ms <- as.numeric(mocap_data$time_ms) * 1000
head(mocap_data)

```

```{r}

path <- file.path("~", "Documents", "Faboratory Stuff", "soft-robotics-simulations", "data", "raise_rhand_mocap_cleaned.csv")
write.csv(mocap_data, path, row.names = FALSE)

```

