---
title: "Mocap Data Analysis for 06/23/2025"
output: html_notebook
---


```{r}

library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)
library(corrr)
library(reshape2)

```

```{r}

mocap_data <- read.csv("/Users/teresanguyen/Documents/Faboratory Stuff/soft-robotics-simulations/raw_data/double_lat_062325.csv", skip = 3)
mocap_data <- mocap_data[-1,]
colnames(mocap_data)
head(mocap_data)

```

```{r}


mocap_data <- mocap_data[, !(colnames(mocap_data) %in% c(  "dancepad:Marker 001", "dancepad:Marker 001", "dancepad:Marker 0010",
  "dancepad:Marker 0010", "dancepad:Marker 0010", "dancepad:Marker 002",
  "dancepad:Marker 002", "dancepad:Marker 002", "dancepad:Marker 004",
  "dancepad:Marker 004", "dancepad:Marker 004", "dancepad:Marker 007",
  "dancepad:Marker 007", "dancepad:Marker 007", "dancepad:Marker 008",
  "dancepad:Marker 008", "dancepad:Marker 008", "dancepad:Marker 009",
  "dancepad:Marker 009", "dancepad:Marker 009", "dancepad:Marker 011",
  "dancepad:Marker 011", "dancepad:Marker 011",   "dancepad", "dancepad.1", "dancepad.2", "dancepad.3",
  "dancepad.4", "dancepad.5", "dancepad.6", "dancepad.Marker.001",
  "dancepad.Marker.001.1", "dancepad.Marker.001.2", "dancepad.Marker.002",
  "dancepad.Marker.002.1", "dancepad.Marker.002.2", "dancepad.Marker.003",
  "dancepad.Marker.003.1", "dancepad.Marker.003.2", "dancepad.Marker.004",
  "dancepad.Marker.004.1", "dancepad.Marker.004.2", "dancepad.Marker.005",
  "dancepad.Marker.005.1", "dancepad.Marker.005.2", "dancepad.Marker.006",
  "dancepad.Marker.006.1", "dancepad.Marker.006.2", "dancepad.Marker.007",
  "dancepad.Marker.007.1", "dancepad.Marker.007.2", "dancepad.Marker.008",
  "dancepad.Marker.008.1", "dancepad.Marker.008.2", "dancepad.Marker.009",
  "dancepad.Marker.009.1", "dancepad.Marker.009.2", "dancepad.Marker.0010",
  "dancepad.Marker.0010.1", "dancepad.Marker.0010.2", "dancepad.Marker.011",
  "dancepad.Marker.011.1", "dancepad.Marker.011.2", "dancepad.Marker.001.3",
  "dancepad.Marker.001.4", "dancepad.Marker.001.5", "dancepad.Marker.0010.3",
  "dancepad.Marker.0010.4", "dancepad.Marker.0010.5", "dancepad.Marker.002.3",
  "dancepad.Marker.002.4", "dancepad.Marker.002.5", "dancepad.Marker.004.3",
  "dancepad.Marker.004.4", "dancepad.Marker.004.5", "dancepad.Marker.007.3",
  "dancepad.Marker.007.4", "dancepad.Marker.007.5", "dancepad.Marker.008.3",
  "dancepad.Marker.008.4", "dancepad.Marker.008.5", "dancepad.Marker.009.3",
  "dancepad.Marker.009.4", "dancepad.Marker.009.5", "dancepad.Marker.011.3",
  "dancepad.Marker.011.4", "dancepad.Marker.011.5"))]

colnames(mocap_data)
head(mocap_data)

```

```{r}

joint_map <- c(
  # core
  "rawan_test.rawan_test" = "base",
  "Skeleton.Skeleton" = "base",
  "Skeleton.Ab"       = "abdomen",
  "Skeleton.Chest"    = "chest",
  "Skeleton.Neck"     = "neck",
  "Skeleton.Head"     = "head",
  # shoulders & arms
  "Skeleton.LShoulder" = "left_shoulder",
  "Skeleton.RShoulder" = "right_shoulder",
  "Skeleton.LUArm"     = "left_upper_arm",
  "Skeleton.LUPA"      = "left_upper_arm",
  "Skeleton.LFArm"     = "left_forearm",
  "Skeleton.LFRM"      = "left_forearm",
  "Skeleton.RUArm"     = "right_upper_arm",
  "Skeleton.RUPA"      = "right_upper_arm",
  "Skeleton.RFArm"     = "right_forearm",
  "Skeleton.RFRM"      = "right_forearm",
  "Skeleton.LELB"      = "left_elbow",
  "Skeleton.RELB"      = "right_elbow",
  "Skeleton.LSHO"      = "left_shoulder",
  "Skeleton.RSHO"      = "right_shoulder",
  "Skeleton.LWRB"      = "left_wrist_b",
  "Skeleton.LWRA"      = "left_wrist_a",
  "Skeleton.RWRB"      = "right_wrist_b",
  "Skeleton.RWRA"      = "right_wrist_a",
  "Skeleton.LHand"     = "left_hand",
  "Skeleton.RHand"     = "right_hand",
  # fingers
  "Skeleton.LThumb1"   = "left_thumb1",
  "Skeleton.LThumb2"   = "left_thumb2",
  "Skeleton.LThumb3"   = "left_thumb3",
  "Skeleton.LIndex1"   = "left_index1",
  "Skeleton.LIndex2"   = "left_index2",
  "Skeleton.LIndex3"   = "left_index3",
  "Skeleton.LMiddle1"  = "left_middle1",
  "Skeleton.LMiddle2"  = "left_middle2",
  "Skeleton.LMiddle3"  = "left_middle3",
  "Skeleton.LRing1"    = "left_ring1",
  "Skeleton.LRing2"    = "left_ring2",
  "Skeleton.LRing3"    = "left_ring3",
  "Skeleton.LPinky1"   = "left_pinky1",
  "Skeleton.LPinky2"   = "left_pinky2",
  "Skeleton.LPinky3"   = "left_pinky3",
  "Skeleton.RThumb1"   = "right_thumb1",
  "Skeleton.RThumb2"   = "right_thumb2",
  "Skeleton.RThumb3"   = "right_thumb3",
  "Skeleton.RIndex1"   = "right_index1",
  "Skeleton.RIndex2"   = "right_index2",
  "Skeleton.RIndex3"   = "right_index3",
  "Skeleton.RMiddle1"  = "right_middle1",
  "Skeleton.RMiddle2"  = "right_middle2",
  "Skeleton.RMiddle3"  = "right_middle3",
  "Skeleton.RRing1"    = "right_ring1",
  "Skeleton.RRing2"    = "right_ring2",
  "Skeleton.RRing3"    = "right_ring3",
  "Skeleton.RPinky1"   = "right_pinky1",
  "Skeleton.RPinky2"   = "right_pinky2",
  "Skeleton.RPinky3"   = "right_pinky3",
  # legs & feet
  "Skeleton.LThigh"    = "left_thigh",
  "Skeleton.RThigh"    = "right_thigh",
  "Skeleton.LShin"     = "left_shin",
  "Skeleton.RShin"     = "right_shin",
  "Skeleton.LFoot"     = "left_foot",
  "Skeleton.RFoot"     = "right_foot",
  "Skeleton.LToe"      = "left_toe_marker",
  "Skeleton.RToe"      = "right_toe_marker",
  "Skeleton.LANK"      = "left_ankle",
  "Skeleton.RANK"      = "right_ankle",
  "Skeleton.LHEE"      = "left_heel",
  "Skeleton.RHEE"      = "right_heel",
  # head extras
  "Skeleton.LFHD"      = "left_forehead",
  "Skeleton.LBHD"      = "left_back_head",
  "Skeleton.RFHD"      = "right_forehead",
  "Skeleton.RBHD"      = "right_back_head",
  # spine & torso
  "Skeleton.C7"        = "7_cervical_vertebra",
  "Skeleton.T10"       = "t10",
  "Skeleton.RBAK"      = "right_back",
  "Skeleton.CLAV"      = "clavicle",
  "Skeleton.STRN"      = "sternum",
  # pelvis
  "Skeleton.LASI"      = "left_asi",
  "Skeleton.LPSI"      = "left_psi",
  "Skeleton.RASI"      = "right_asi",
  "Skeleton.RPSI"      = "right_psi",
  "Skeleton.RFIN" = "right_finger",
  "Skeleton.LFIN" = "left_finger",
  "Skeleton.LTHI" = "left_thigh",
  "Skeleton.LKNE" = "left_knee",
  "Skeleton.LTIB" = "left_tibia",
  "Skeleton.RTIB" = "right_tibia",
  "Skeleton.RToe" = "right_toe",
  "Left.Foot" = "left_foot",
  "Right.Foot" = "right_foot",
  "Skeleton.LTOE" = "left_toe",
  "Skeleton.RTHI" = "right_thigh",
  "Skeleton.RKNE" = "right_knee",
  "Skeleton.RTOE" = "right_toe"
  
)

```

```{r}

# names(joint_map) <- gsub("^Skeleton", "rawan_test", names(joint_map))


```

```{r}

# original joint names extracted
colnames(mocap_data)
# Remove suffixes like ".1", ".6", etc. from the original names
original_joint_names <- colnames(mocap_data)

clean_joint_names <- sub("\\.[0-9]+$", "", original_joint_names)

# Replace using the dictionary
renamed_joint_names <- ifelse(
  clean_joint_names %in% names(joint_map),
  joint_map[clean_joint_names],
  original_joint_names
)

# extract data type and axis for combination
axis <- unlist(mocap_data[2, ])

new_colnames <- paste(renamed_joint_names, axis, sep = "_")

# Remove spaces and NA
new_colnames <- gsub("NA", "", new_colnames)
new_colnames <- gsub("__", "_", new_colnames)

mocap_data <- mocap_data[-c(1:2), ]
colnames(mocap_data) <- new_colnames
colnames(mocap_data)[2] <- "time_ms"
colnames(mocap_data)[1] <- "Frame"

# Checks
head(mocap_data)
colnames(mocap_data)

```

```{r}

mocap_data$time_ms <- as.numeric(mocap_data$time_ms) * 1000
head(mocap_data)

```

```{r}

path <- file.path("~", "Documents", "Faboratory Stuff", "soft-robotics-simulations", "data", "intermediatary.csv")
write.csv(mocap_data, path, row.names = FALSE)

```

```{r}

library(readr)

data <- read.csv("/Users/teresanguyen/Documents/Faboratory Stuff/soft-robotics-simulations/data/intermediatary.csv")
head(data)
colnames(data)
```

```{r}

path <- file.path("~", "Documents", "Faboratory Stuff", "soft-robotics-simulations", "cleaned_mocap_data", "double_lat_062325.csv")
write.csv(data, path, row.names = FALSE)

```